### PR TITLE
contributors script added and README.md updated with it

### PR DESCRIPTION
**Pull request by Rafi993**
contributors script added which gets the name of the repo and generates list of contributors images as a markdown file after resizing their profile pic to standard size and README.md updated with it.

### CODE REVIEW

**Comment by Rafi993** [comment]
You could see the fork here https://github.com/Rafi993/Python-Scripts to see how it is displayed at bottom

**Comment by Logan1x** [comment]
did you added your name to the list yet?

**Comment by Rafi993** [comment]
Yes I did. Could you repo link to this git page http://www.logan1x.me/Python-Scripts/

**Comment by Logan1x** [comment]
> Could you post repo the link to this git page

Didn't Understand?😕

**Comment by Rafi993** [comment]
I have created a git page for this repo here it is https://rafi993.github.io/python_scripts_page/ Here is the repo link for git page https://github.com/Rafi993/python_scripts_page. It is very rudimentary page I built in a couple of minutes so it could use some improvements.

**Comment by Rafi993** [comment]
It the above git page is ok I could merge its code with  your repo / branch that your git page is currently pointing to now.

**Comment by Logan1x** [comment]
You have written tags (that's lot work for me 😅). Thank you for making this project alive again.

**Comment by Logan1x** [comment]
the last script yt.py does not have [warnings](https://github.com/Logan1x/Python-Scripts#note). Please add them.

**Comment by Logan1x** [comment]
Hey @Rafi993, I've added you as a maintainer of this project. Check [this]( https://github.com/Logan1x/Python-Scripts/invitations) link if you choose this task😛.

**Comment by Rafi993** [comment]
I have added the git page source inside docs folder. Now just point docs folder in master in git page settings. So that it will become new git page.

**Comment by Logan1x** [comment]
@Rafi993 I've done this and now I want to config Travis CI for this project. So if you know how to integrate CI, you could help me out😄

**Comment by Rafi993** [comment]
you just need to add dependencies for all the scripts in a single requirement.txt  and we need to write unit tests. So our .travis.yml will look like this

```
language: python
python:
  - "3.3"
  - "3.4"
  - "3.6"
# command to install dependencies
install:
  - pip install coveralls
  - pip install pep8
  - pip install -r requirements.txt
# command to run tests
script:
  - pep8 --max-line-length 5000 bin
  - pytest
after_success:
  - coveralls
```

**Comment by Logan1x** [comment]
I've created requirement.txt, I'll add dependencies as soon as I get time.

**Comment by Logan1x** [comment]
So where do I need to add .travis.yml? in the repo or at Travis ci config page?

**Comment by Rafi993** [comment]
https://github.com/Logan1x/Python-Scripts/blob/master/.travis.yml

**Comment by Logan1x** [comment]
image
Are those setting are right ?

**Pull request merged**
