### PR TITLE
Added a python script to download high quality videos and audio using youtube-dl.

### PR DESCRIPTION
**Pull request by Souldiv**
- can download playlists as well. Just give the playlist link.
- can be used to download single video files or extract audio from a video.

### CODE REVIEW

**Comment by Souldiv** [comment]
#1

**Comment by Logan1x** [comment]
@Souldiv merge your readme.md into [this](https://github.com/Logan1x/Python-Scripts/blob/master/README.md) and add commands to run script.

**Comment by Logan1x** [comment]
@Souldiv merge your readme.md into [this](https://github.com/Logan1x/Python-Scripts/blob/master/README.md) and add commands to run script.

**Comment by Logan1x** [comment]
Please put your readme,md description before "Y". These scripts are sorted alphabetically and you need to change the highlighted font size of videodownloader and sub points like about and command. to change the font use `##` in front of videodownloader and `###` for subpoints.

**Comment by Logan1x** [comment]
> https://github.com/Logan1x/Python-Scripts/pull/49#issuecomment-338367995

Ok sorry my mistake these changes have already been done. merging you pr😊

**Comment by Logan1x** [comment]
Thank you for your help, and congrats on your first pr to this repo!!🎉

If you like this repo don't  forget to 🌟

**Pull request merged**
