### PR TITLE
Add middle and top alignment Issue #26

### PR DESCRIPTION
**Pull request by ValentinChCloud**
Hello, I see you got some issues with the alignment of the picture #26 . I tried some options, and the option "top" seem to fit your request. I allow myself to try since @sagar-kalra asked for help. Hope it will help you :)
P.S : I left 3 options to see the difference.

Valentin

### CODE REVIEW

**Comment by Logan1x** [comment]
@ValentinChCloud  i like the third one.😊 what's your opinion?

**Comment by ValentinChCloud** [comment]
I agree :D

**Comment by Logan1x** [comment]
So delete the others. so that I can merge

**Comment by ValentinChCloud** [comment]
Done

**Comment by Logan1x** [comment]
Thanks for the contribution @ValentinChCloud .😊

**Pull request merged**
