### PR TITLE
Update README Docs, Added script

### PR DESCRIPTION
**Pull request by toonarmycaptain**
Facebook bot README - Added link to medium post explaining code.
README - added name to contributer list
Added script to find large files, and README
Added findlargefiles.py with README

### CODE REVIEW

**Comment by Logan1x** [comment]
there are some conflicts can you resolve them?

**Comment by toonarmycaptain** [comment]
How do I do that?

**Comment by toonarmycaptain** [comment]
Ok I think I fixed what I needed to by deleting what I had, reforking and creating a new pull.

**Comment by Logan1x** [comment]
👍

**Pull request closed without merging**
