### PR TITLE
Move Scripts to the Root

### LINKED ISSUE #2: Redesign The Repo
Script in the folder is not looking good to me, If you can put them outside of folder [here](https://github.com/Logan1x/Python-Scripts), this would look more fine.

Add Your name in readme.md after contributing😊.

### PR DESCRIPTION
**Pull request by KayvanMazaheri**
Closes #2 .

### CODE REVIEW

**Comment by Logan1x** [comment]
I'll add this pr on 1 oct so that it will be counted in hacktoberfest. If you don't know about this then let me know i'll give you info 😊 and **Thanks for all the help **

**Comment by KayvanMazaheri** [comment]
@Logan1x 
No problem. Let me know if it needs any further changes.

**Comment by Logan1x** [comment]
Sure @KayvanMazaheri  and do you know about hacktoberfest?

**Comment by KayvanMazaheri** [comment]
@Logan1x Yeah, But I'm not sure if this PR counts because it is created before October 1st. :smile:

**Comment by Logan1x** [comment]
That why i am waiting let's check on 1st. also my 1 pr is on halt for this 😜.

**Comment by Logan1x** [comment]
Thanks for the help @KayvanMazaheri 😊.

**Pull request merged**
