### PR TITLE
created a dice_simulator.py program

### PR DESCRIPTION
**Pull request by iyanuashiri**
This script generates simulates a 6-sided dice. 
It is a good beginner script for Python programmers to get their hands wet

### CODE REVIEW

**Comment by Logan1x** [comment]
why there is **.idea** folder? and all the python scripts are now moved to /bin folder please update it.

**Comment by iyanuashiri** [comment]
Please I have tried all I know, including Google search. I have tried revert, reset and..... Can you provide a guide on removing the folder? I appreciate the response

**Comment by iyanuashiri** [comment]
I have fixed it.

**Comment by Logan1x** [comment]
You deleted the .idea folder that's great, now move your scripts into /bin folder. 

Just unfork and fork again my repo you will see changes in repo then add your python scripts in /bin folder and then PR😊.
if you need any pr in the between process you can always paste your comment here.

**Comment by iyanuashiri** [comment]
I followed your instruction and I have completed a PR. Should I delete this pull request?

**Comment by Logan1x** [comment]
Pinging! Are you working on this?

**Comment by iyanuashiri** [comment]
At all. Waiting for a merge.

**Comment by Logan1x** [comment]
@iyanuashiri  you have to move script in /bin folder and you also have to give description in readme.md after then i can merge.

if you are not able to see the /bin folder in your forked repo than just unfork it and fork it again.

**Pull request closed without merging**
