### PR TITLE
Moved scripts

### PR DESCRIPTION
**Pull request by toonarmycaptain**
Moved scripts to root folder.

### CODE REVIEW

**Comment by Logan1x** [comment]
It's Very good work but i am sorry i can not merge this pull request because you didn't assigned to work on this next time you give patch for any repo please comment on issue... 
**Thanks** and really sorry for this😞

**Comment by Logan1x** [comment]
well if you want to work on this repo let me know i have one issue in mind😊

**Comment by Logan1x** [comment]
I forgot right now but i'll let you know when it comes to my mind😁

**Comment by Logan1x** [comment]
I need to change the readme description of facebook posing bot
[link ](https://github.com/Logan1x/Python-Scripts#facebook-auto-post) 
add this line - If you want to understand this code you can visit [here]( https://medium.com/@Logan1x/facebook-posting-bot-98f20ff5da44).

**Comment by Logan1x** [comment]
iF you are working on this let me know

**Comment by toonarmycaptain** [comment]
I'll work on it.

**Comment by toonarmycaptain** [comment]
Let me know when you're ready to commit. Also happy to add a script if desired.

**Comment by Logan1x** [comment]
I am always ready you just have to submit pr for this😊

**Pull request closed without merging**
