### PR TITLE
Script to group file by type added

### PR DESCRIPTION
**Pull request by Rafi993**
Script to group file by type added directories in that folder are ignored only files at root level is considered

### CODE REVIEW

**Comment by Logan1x** [comment]
Thank you for contributing to making this project better.😊I hope you liked the project.

**Comment by Logan1x** [comment]
Hey, @Rafi993  The Scripts are not arranged alphabetically in [`readme.md`](https://github.com/Logan1x/Python-Scripts/blob/master/README.md), Would you to fix them?

**Comment by Rafi993** [comment]
sure I will. And may be we can put a small git page where these scripts are searchable. Something like [this ](http://ramdajs.com/docs/)

**Comment by Logan1x** [comment]
Right now it is hosted [here](http://www.logan1x.me/Python-Scripts/) on GitHub pages theme, If you have a good one send a PR 😅

**Comment by Rafi993** [comment]
Awesome

**Pull request merged**
