### PR TITLE
image to vector data

### PR DESCRIPTION
**Pull request by apuayush**
converts images to a data vector , can be used for image prediction in deep learning.

### CODE REVIEW

**Comment by Logan1x** [comment]
@apuayush add the description of your project to readme md and add yourself to contributors list. If you need any help check other pr's or comment here😊

**Comment by apuayush** [comment]
i have added my script descriptions but i think my commit shows that i changed all the files because of using same files in two different os... if you think it is a problem notify me else merge if you feel like

**Comment by apuayush** [comment]
sorry i had a commit issue . now fixed . merge if you feel like.

**Comment by Logan1x** [comment]
Tip for Next time when you give pr in an org , clone the repo again and add your changes again. 😊

**Comment by apuayush** [comment]
Yea sure.. thanx i will keep that in mind . We should actually create a different branch.

**Pull request merged**
