### PR TITLE
Add highcharts loader

### PR DESCRIPTION
**Pull request by lionasp**

### CODE REVIEW

**Comment by Logan1x** [comment]
Add requirements.txt file and add your name to contributors

**Comment by lionasp** [comment]
Updated pull request

**Comment by Logan1x** [comment]
you need to arrange script description alphabetically and rename the name of `requirement.txt`

**Comment by Logan1x** [comment]
Pinging! Are you working on this?

**Comment by lionasp** [comment]
Yes, sorry for delay.

**Comment by lionasp** [comment]
Updated. Check it, please

**Comment by Logan1x** [comment]
@lionasp thanks for changes 😊

**Pull request merged**
