### PR TITLE
Twitter retweet bot

### PR DESCRIPTION
**Pull request by iyanuashiri**
This is a Twitter bot that retweets a tweet based on an hashtag

### CODE REVIEW

**Comment by Logan1x** [comment]
@iyanuashiri  add the description for your script in readme.md.

**Comment by Logan1x** [comment]
Add a description for dice simulator, Do not make new pr when you add description. and no need to delete that pr.

**Comment by iyanuashiri** [comment]
I have added a description of the dice_simulator script, what do I do next?

**Comment by Logan1x** [comment]
Can you give me link of pr where you made changes  or tagbme there.

**Comment by iyanuashiri** [comment]
How do I give you the link of the PR?

**Comment by Logan1x** [comment]
just type @ and suggested name will arrive.

**Pull request merged**
