### PR TITLE
Sentiment Analysis of Twitter Feeds

### PR DESCRIPTION
**Pull request by niharikakrishnan**
Displays the sentiment value in terms of positive, negative and neutral. 
Also displays 5 random tweets on the issue of demonetisation and gives it's polarity and sentiment.
Various analysis is plotted using graphs.

### CODE REVIEW

**Comment by Logan1x** [comment]
Add commits of this PR in last one by choosing the same branch.

**Comment by niharikakrishnan** [comment]
I added the the requirement.txt file and made the necessary changes in readme.md

**Comment by niharikakrishnan** [comment]
I understood the mistake i did. Hence, deleted the other Update readme.md pull request.

**Comment by Logan1x** [comment]
Thanks @niharikakrishnan for contribution 🎉.

If you liked the project don't forget to give it ⭐.

**Comment by niharikakrishnan** [comment]
Thanks @Logan1x  for all the help. It was fun contributing.

**Pull request merged**
