### PR TITLE
Added Script To Collect Data From Serial Monitor And Save It To Firebase

### PR DESCRIPTION
**Pull request by MadhavBahlMD**
Added Script To Collect Data From Serial Monitor And Save It To Firebase Database

### CODE REVIEW

**Comment by Logan1x** [comment]
Add your name to contributor's list 😊

**Comment by MadhavBahlMD** [comment]
Done 😊

**Comment by Logan1x** [comment]
Thnaks For contributing @MadhavBahlMD  😊

**Comment by MadhavBahlMD** [comment]
I love to contribute in open source projects 😊 will see if there are more
scripts i can make.

**Pull request merged**
